// import { Claim } from "@/types/types";

// export const mockClaims: Claim[] = [
//   {
//     patient_id: "P1",
//     patient_name: "John Smith",
//     billing_code: "B1001",
//     amount: 1675.5,
//     insurance_provider: "Blue Shield",
//     payment_status: "Pending",
//     claim_date: "2025-03-25",
//   },
//   {
//     patient_id: "P2",
//     patient_name: "Sarah Johnson",
//     billing_code: "B2002",
//     amount: 2310.09,
//     insurance_provider: "Medicare",
//     payment_status: "Approved",
//     claim_date: "2025-01-05",
//   },
//   {
//     patient_id: "P3",
//     patient_name: "Robert Chen",
//     billing_code: "B3003",
//     amount: 4945.57,
//     insurance_provider: "Aetna",
//     payment_status: "Pending",
//     claim_date: "2025-03-04",
//   },
//   {
//     patient_id: "P4",
//     patient_name: "Lisa Williams",
//     billing_code: "B4004",
//     amount: 8338.89,
//     insurance_provider: "UnitedHealth",
//     payment_status: "Denied",
//     claim_date: "2025-03-20",
//   },
//   {
//     patient_id: "P5",
//     patient_name: "Michael Garcia",
//     billing_code: "B5005",
//     amount: 3220.05,
//     insurance_provider: "Cigna",
//     payment_status: "Denied",
//     claim_date: "2025-02-21",
//   },
// ];

import { Claim } from "@/types/types";

export const mockClaims: Claim[] = [
  {
    patient_id: "P1",
    patient_name: "John Smith",
    billing_code: "B1001",
    amount: 1675.5,
    insurance_provider: "Blue Shield",
    payment_status: "Pending",
    claim_date: "2025-03-25",
  },
  {
    patient_id: "P2",
    patient_name: "Sarah Johnson",
    billing_code: "B2002",
    amount: 2310.09,
    insurance_provider: "Medicare",
    payment_status: "Approved",
    claim_date: "2025-01-05",
  },
  {
    patient_id: "P3",
    patient_name: "Robert Chen",
    billing_code: "B3003",
    amount: 4945.57,
    insurance_provider: "Aetna",
    payment_status: "Pending",
    claim_date: "2025-03-04",
  },
  {
    patient_id: "P4",
    patient_name: "Lisa Williams",
    billing_code: "B4004",
    amount: 8338.89,
    insurance_provider: "UnitedHealth",
    payment_status: "Denied",
    claim_date: "2025-03-20",
  },
  {
    patient_id: "P5",
    patient_name: "Michael Garcia",
    billing_code: "B5005",
    amount: 3220.05,
    insurance_provider: "Cigna",
    payment_status: "Denied",
    claim_date: "2025-02-21",
  },
  {
    patient_id: "P6",
    patient_name: "Emily Davis",
    billing_code: "B6006",
    amount: 2875.75,
    insurance_provider: "Humana",
    payment_status: "Pending",
    claim_date: "2025-03-10",
  },
  {
    patient_id: "P7",
    patient_name: "Daniel Lee",
    billing_code: "B7007",
    amount: 1350.0,
    insurance_provider: "Kaiser Permanente",
    payment_status: "Approved",
    claim_date: "2025-01-18",
  },
  {
    patient_id: "P8",
    patient_name: "Sophia Martinez",
    billing_code: "B8008",
    amount: 4680.25,
    insurance_provider: "Blue Cross",
    payment_status: "Pending",
    claim_date: "2025-02-07",
  },
  {
    patient_id: "P9",
    patient_name: "William Brown",
    billing_code: "B9009",
    amount: 780.9,
    insurance_provider: "Aetna",
    payment_status: "Approved",
    claim_date: "2025-02-11",
  },
  {
    patient_id: "P10",
    patient_name: "Ava Wilson",
    billing_code: "B1010",
    amount: 999.99,
    insurance_provider: "Cigna",
    payment_status: "Denied",
    claim_date: "2025-03-02",
  },
  {
    patient_id: "P11",
    patient_name: "James Anderson",
    billing_code: "B1011",
    amount: 4125.0,
    insurance_provider: "UnitedHealth",
    payment_status: "Pending",
    claim_date: "2025-01-29",
  },
  {
    patient_id: "P12",
    patient_name: "Mia Thomas",
    billing_code: "B1012",
    amount: 2387.45,
    insurance_provider: "Medicaid",
    payment_status: "Approved",
    claim_date: "2025-03-15",
  },
  {
    patient_id: "P13",
    patient_name: "Logan Jackson",
    billing_code: "B1013",
    amount: 6840.6,
    insurance_provider: "Blue Shield",
    payment_status: "Denied",
    claim_date: "2025-03-11",
  },
  {
    patient_id: "P14",
    patient_name: "Isabella White",
    billing_code: "B1014",
    amount: 1525.25,
    insurance_provider: "Medicare",
    payment_status: "Approved",
    claim_date: "2025-02-23",
  },
  {
    patient_id: "P15",
    patient_name: "Ethan Harris",
    billing_code: "B1015",
    amount: 2999.0,
    insurance_provider: "Kaiser Permanente",
    payment_status: "Pending",
    claim_date: "2025-01-16",
  },
  {
    patient_id: "P16",
    patient_name: "Grace Clark",
    billing_code: "B1016",
    amount: 3895.15,
    insurance_provider: "Humana",
    payment_status: "Denied",
    claim_date: "2025-02-10",
  },
  {
    patient_id: "P17",
    patient_name: "Lucas Lewis",
    billing_code: "B1017",
    amount: 2100.5,
    insurance_provider: "Aetna",
    payment_status: "Approved",
    claim_date: "2025-03-12",
  },
  {
    patient_id: "P18",
    patient_name: "Zoe Young",
    billing_code: "B1018",
    amount: 4760.8,
    insurance_provider: "Cigna",
    payment_status: "Pending",
    claim_date: "2025-03-19",
  },
  {
    patient_id: "P19",
    patient_name: "Benjamin Hall",
    billing_code: "B1019",
    amount: 3255.0,
    insurance_provider: "Blue Cross",
    payment_status: "Denied",
    claim_date: "2025-01-27",
  },
  {
    patient_id: "P20",
    patient_name: "Chloe Allen",
    billing_code: "B1020",
    amount: 2444.4,
    insurance_provider: "Medicaid",
    payment_status: "Approved",
    claim_date: "2025-03-08",
  },
  {
    patient_id: "P21",
    patient_name: "Elijah Scott",
    billing_code: "B1021",
    amount: 3199.95,
    insurance_provider: "Blue Shield",
    payment_status: "Pending",
    claim_date: "2025-02-28",
  },
  {
    patient_id: "P22",
    patient_name: "Amelia Green",
    billing_code: "B1022",
    amount: 1840.3,
    insurance_provider: "Kaiser Permanente",
    payment_status: "Approved",
    claim_date: "2025-03-05",
  },
  {
    patient_id: "P23",
    patient_name: "Mason Baker",
    billing_code: "B1023",
    amount: 5788.25,
    insurance_provider: "Humana",
    payment_status: "Denied",
    claim_date: "2025-02-18",
  },
  {
    patient_id: "P24",
    patient_name: "Lily Adams",
    billing_code: "B1024",
    amount: 2680.65,
    insurance_provider: "UnitedHealth",
    payment_status: "Approved",
    claim_date: "2025-01-12",
  },
  {
    patient_id: "P25",
    patient_name: "Henry Nelson",
    billing_code: "B1025",
    amount: 3420.5,
    insurance_provider: "Blue Cross",
    payment_status: "Pending",
    claim_date: "2025-03-14",
  },
];

